#
#Sun Mar 22 20:24:17 COT 2026
acceptInsecureCerts=false
browserName=MicrosoftEdge
ms\:edgeOptions={args\=[start-maximized, inprivate, ignore-certificate-errors, disable-popup-blocking, remote-allow-origins\=*, start-maximized, inprivate, ignore-certificate-errors, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
