#
#Sun Mar 22 20:15:18 COT 2026
goog\:chromeOptions={args\=[--headless\=new, --disable-gpu, --no-sandbox, --disable-dev-shm-usage, --window-size\=1920,1080, --remote-allow-origins\=*, --headless\=new, --disable-gpu, --no-sandbox, --disable-dev-shm-usage, --window-size\=1920,1080, --remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
