#
#Mon Mar 23 22:17:32 COT 2026
acceptInsecureCerts=false
browserName=MicrosoftEdge
ms\:edgeOptions={args\=[start-maximized, inprivate, ignore-certificate-errors, disable-popup-blocking, start-maximized, inprivate, ignore-certificate-errors, disable-popup-blocking, remote-allow-origins\=*], extensions\=[]}
