name: Serenity BDD Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test
        env:
          WEBDRIVER_DRIVER: chrome

      - name: Upload Serenity Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity/